services:
  game-key:
    container_name: game-key
    build:
      context: .
      dockerfile: Dockerfile
      target: development
      args:
        APP_USER: ${UID:-1000}
        APP_GROUP: ${GID:-1000}
        CURRENT_ENVIRONMENT: development
    volumes:
      - ./:/app
    ports:
      - "80:80"
    networks:
      - internal
  mysql_db:
      container_name: game-key-db
      image: mysql:8.0-oracle
      environment:
          - MYSQL_DATABASE=game-key-db
          - MYSQL_RANDOM_ROOT_PASSWORD=yes
          - MYSQL_USER=db-user
          - MYSQL_PASSWORD=db-password
      volumes:
          - ./docker-db:/var/lib/mysql
      ports:
          - "3306:3306"
      networks:
          - internal
networks:
  internal:
